### ISSUE TITLE
Tests not working

### ISSUE THREAD

**Issue by lisamarie616** [learn-co-curriculum/sql-aggregate-functions-lab#6]
All of the tests in the lab pass before any code is entered, except the one for #average_gpa_for_9th_grade.

Looks like all of the methods are included/completed at the bottom of the spec file.

**Comment by AnnJohn** [comment]
hi this should be updated. Thanks!

**Comment by dannyd4315** [comment]
Hi, this is still the case. The tests all pass. The methods are still at the bottom of student_spec.rb 

They will need to be deleted. Have deleted them locally for the moment

**Comment by AnnJohn** [comment]
Should be good to go now. The methods have been deleted. Thanks again
